name: Distribution Builds

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    env:
      PACKR: packr.jar
      JRE_LINUX: jre-linux.tar.gz
      JRE_WINDOWS: jre-windows.zip
      LINUX_ZIP: gdx-graph-linux.zip
      WINDOWS_ZIP: gdx-graph-windows.zip
    runs-on: ubuntu-latest
    steps:
      - name: Install APT dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
          TZ: Europe/London
        run: sudo apt-get install -y wget
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Download Packr
        env:
            PACKR_URL: https://github.com/libgdx/packr/releases/download/4.0.0/packr-all-4.0.0.jar
            JRE_LINUX_URL: https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.3%2B7/OpenJDK17U-jre_x64_linux_hotspot_17.0.3_7.tar.gz
            JRE_WINDOWS_URL: https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.3%2B7/OpenJDK17U-jre_x64_windows_hotspot_17.0.3_7.zip
        run: |
          wget -qO $PACKR $PACKR_URL
          wget -qO $JRE_LINUX $JRE_LINUX_URL
          wget -qO $JRE_WINDOWS $JRE_WINDOWS_URL
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --no-daemon build
      - name: Package Linux
        env:
          OUTDIR: out-linux
        run: |
          java -jar $PACKR \
            --platform linux64 \
            --jdk $JRE_LINUX \
            --useZgcIfSupportedOs \
            --executable gdx-graph-editor \
            --classpath desktop/build/libs/desktop-0.6.2-SNAPSHOT.jar \
            --mainclass com.gempukku.libgdx.graph.desktop.DesktopLauncher \
            --vmargs Xmx1G \
            --resources core/assets \
            --output $OUTDIR
          tar -czf $LINUX_ZIP $OUTDIR
      - name: Package Windows
        env:
          OUTDIR: out-windows
        run: |
          java -jar $PACKR \
            --platform windows64 \
            --jdk $JRE_WINDOWS \
            --useZgcIfSupportedOs \
            --executable gdx-graph-editor \
            --classpath desktop/build/libs/desktop-0.6.2-SNAPSHOT.jar \
            --mainclass com.gempukku.libgdx.graph.desktop.DesktopLauncher \
            --vmargs Xmx1G \
            --resources core/assets \
            --output $OUTDIR
          tar -czf $WINDOWS_ZIP $OUTDIR
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            $LINUX_ZIP
            $WINDOWS_ZIP
